spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL.HOST}/datn?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL.USERNAME}
    password: ${MYSQL.PASSWORD}
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 50MB
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true

application:
  security:
    jwt:
      secret-key: d63c169a95a1f1dbaa6fefa225bbee99189cd07374d56bd0cf7e9f6be712cc92
      expiration: 86400000
      refresh-token:
        expiration: 186400000
server:
  port: 8080

