spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datn?useUnicode=yes
    username: ${MYSQL.USERNAME}
    password: ${MYSQL.PASSWORD}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 10MB
      enabled: true
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: off
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile


springdoc:
  api-docs:
    path: /api-docs

application:
  frontend:
    url: ${BASE_URL_FRONT_END}
  security:
    jwt:
      secret-key: d63c169a95a1f1dbaa6fefa225bbee99189cd07374d56bd0cf7e9f6be712cc92
      expiration: 15 # 1h 30m
      refresh-token:
        expiration: 10080 # 7d
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

  payment:
    vnpay:
      payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      returnUrl: ${BASE_URL_GREAMZ}/api/v1/payment/vnpay/call-back
      tmnCode: ${VNPAY_TMN}
      secretKey: ${VNPAY_SECRET}
      apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
    paypal:
      client-id: ${PAYPAL_ID}
      client-sec: ${PAYPAL_SEC}
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG

