spring:
  security:
    oauth2:

      client:
        registration:
          google:
            client-id: 914583679856-b2cqa56h84bor2ovdct6imlb84vgq912.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/oauth2/callback/"
            scope:
              - email
              - profile
              - openid

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL.HOST}/datn?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL.USERNAME}
    password: ${MYSQL.PASSWORD}
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 50MB
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  jackson:
     .
springdoc:
  api-docs:
    path: /api-docs
application:
  security:
    jwt:
      secret-key: d63c169a95a1f1dbaa6fefa225bbee99189cd07374d56bd0cf7e9f6be712cc92
      expiration: 86400000
      refresh-token:
        expiration: 186400000
server:
  port: 8080

