spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 174279917949-jldul43lq0as6pdkda9o51qbacf2ljuj.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL.HOST}/datn?useUnicode=yes&autoReconnect=true
    username: ${MYSQL.USERNAME}
    password: ${MYSQL.PASSWORD}
    hikari:
      max-lifetime: 54000

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 5MB
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
springdoc:
  api-docs:
    path: /api-docs

application:
  security:
    jwt:
      secret-key: d63c169a95a1f1dbaa6fefa225bbee99189cd07374d56bd0cf7e9f6be712cc92
      expiration: 600000
      refresh-token:
        expiration: 864000000
  payment:
    vnpay:
      payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      returnUrl: http://localhost:3000/order/vnpay
      tmnCode: KAZQ6EDF
      secretKey: SFPMQNPZIKBZLXFEPKXQXSLOXMSHTQIB
      apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

server:
  port: 8080

